---
title: Finetunemusic
timezone: Europe/Amsterdam
collections:
  posts:
    title: Images
    output: true
  music:
    title: Music
    output: true
  uploads:
    title: Uploads
    output: true
  videos:
    title: Videos
    output: true
  voice-overs:
    title: Voice-overs
    output: true
defaults:
- scope:
    path: ''
    type: videos
  values:
    titel: 
    type:
    - vimeo
    - youtube
    video: 026292034
    samenvatting: 
    audio: 
    layout: video
destination: local
keep_files:
- assets
exclude:
- node_modules
- source
- other
- package.json
- gulpfile.js
- README.md
- ".DS_Store"
