---
title: Finetunemusic
timezone: Europe/Amsterdam
collections:
  posts:
    title: Development
    output: true
  music:
    title: Music
    output: false
  uploads:
    title: Uploads
    output: true
  videos:
    title: Videos
    output: true
  voice-overs:
    title: Voice-overs
    output: false
defaults:
- scope:
    path: ''
    type: videos
  values:
    embed: 'Share' vanuit Vimeo en 'Delen' vanuit YouTube
    image:
    summary:
    audio: 
    layout: video
- scope:
    path: ''
    type: music
  values:
    file:
- scope:
    path: ''
    type: voice-overs
  values:
    file:
exclude:
- node_modules
- gulpfile.js
- package.json
- ".DS_Store"
- README.md
- other
- CNAME
- package-lock.json
- _uploads/backup
