# name: Your New Jekyll Site
# markdown: redcarpet
# highlighter: pygments # or rouge or null
# exclude: ["node_modules", "gulpfile.js", "package.json"]

title: Finetunemusic
timezone: Europe/Amsterdam
collections:
  posts:
    title: Development
    output: true
  music:
    title: Music
    output: false
  uploads:
    title: Uploads
    output: true
  videos:
    title: Videos
    output: true
  voice-overs:
    title: Voice-overs
    output: false
defaults:
- scope:
    path: ''
    type: videos
  values:
    is from vimeo: true
    number: 026292034
    summary:
    audio:
    layout: video
- scope:
    path: ''
    type: music
  values:
    file:
- scope:
    path: ''
    type: voice-overs
  values:
    file:
exclude: ["node_modules", "gulpfile.js", "package.json", ".DS_Store", "README.md", "other", "CNAME", "package-lock.json", "_uploads/backup"]
