---
title: Finetunemusic
timezone: Europe/Amsterdam
collections:
  posts:
    title: Languages
    output: true
  music:
    title: Music
    output: false
  sound_logos:
    title: Sound logos
    output: false
  uploads:
    title: Uploads
    output: true
  de:
    title: Videos (DE)
    output: true
  en:
    title: Videos (EN)
    output: true
  video:
    title: Videos (NL)
    output: true
defaults:
- scope:
    path: ''
    type: video
  values:
    language: Dutch
    client: Migloko
    embed: Insert iframe code
    image: 
    description: |-
      ## Project

      Samen met regisseur Joshua Maldonado produceerden we de muziekvideo ‘White Wolf’. De witte en de zwarte wolf symboliseren het goede en het kwade van de mens, vanuit dit concept gaven we zowel het beeld als de muziek vorm.

      ## Audio

      Fine Tune Music produceerde de muziek onder leiding van Marcel Davids. In samenwerking met de Litouwse zangeres en songwriter Migloko kwamen de lyrics en vocalen tot stand.
    pages:
    - 
    layout: video
- scope:
    path: ''
    type: en
  values:
    permalink: "/en/video/:path"
    language: English
    client: Migloko
    embed: Insert iframe code
    image: 
    description: |-
      ## Project

      In collaboration with director Joshua Maldonado we produced this music video, titled ‘White Wolf’. The white wolf and the black wolf symbolize the good and evil side of mankind. With this duality in mind, we created both the visuals and the music.

      ## Audio

      Fine Tune Music produced the music, supervised by Marcel Davids. The lyrics and vocals were created together with singer/songwriter Migloko from Lithuania.
    pages:
    - 
    layout: video
- scope:
    path: ''
    type: de
  values:
    permalink: "/de/video/:path"
    language: German
    client: Migloko
    embed: Insert iframe code
    image: 
    description: |-
      ## Project

      In collaboration with director Joshua Maldonado we produced this music video, titled ‘White Wolf’. The white wolf and the black wolf symbolize the good and evil side of mankind. With this duality in mind, we created both the visuals and the music.

      ## Audio

      Fine Tune Music produced the music, supervised by Marcel Davids. The lyrics and vocals were created together with singer/songwriter Migloko from Lithuania.
    pages:
    - 
    layout: video
- scope:
    path: ''
    type: music
  values:
    file: 
    client: Hanze Hogeschool
    pages:
    - 
- scope:
    path: ''
    type: sound_logos
  values:
    file: 
sass:
  sass_dir: _sass
  style: compressed
cdn: https://res.cloudinary.com/roosdorp/image/fetch
host: https://finetunemusic.nl/
basehref: http://finetunemusic.nl
urlext: 
exclude:
- node_modules
- gulpfile.js
- package.json
- ".DS_Store"
- README.md
- other
- CNAME
- package-lock.json
- _uploads/backup
