---
title: Finetunemusic
timezone: Europe/Amsterdam
collections:
  posts:
    title: Languages
    output: true
  music:
    title: Music
    output: false
  uploads:
    title: Uploads
    output: true
  videos:
    title: Videos
    output: true
  voice-overs:
    title: Voice-overs
    output: false
defaults:
- scope:
    path: ''
    type: videos
  values:
    language: Dutch
    name: White Wolf
    embed: Insert iframe code
    image: 
    summary: Maecenas consequat lacus a felis dapibus egestas. Vivamus urna enim,
      interdum eu tempor eu, posuere quis diam. Quisque quis orci dignissim, eleifend
      massa vel, egestas nisi nam ac velit mauris.
    audio: Nemo enim ipsam voluptatem quia voluptas sit aspernatur aut odit aut fugit,
      sed quia consequuntur magni dolores eos qui ratione voluptatem sequi nesciunt.
    layout: video
- scope:
    path: ''
    type: music
  values:
    file: 
- scope:
    path: ''
    type: voice-overs
  values:
    file: 
exclude:
- node_modules
- gulpfile.js
- package.json
- ".DS_Store"
- README.md
- other
- CNAME
- package-lock.json
- _uploads/backup
