---
title: Finetunemusic
timezone: Europe/Amsterdam
collections:
  posts:
    title: Languages
    output: true
  music:
    title: Music
    output: false
  uploads:
    title: Uploads
    output: true
  en:
    title: Videos (EN)
    output: true
  video:
    title: Videos (NL)
    output: true
  voice-overs:
    title: Voice-overs
    output: false
defaults:
- scope:
    path: ''
    type: video
  values:
    client: Migloko
    embed: Insert iframe code
    image:
    summary: Maecenas consequat lacus a felis dapibus egestas. Vivamus urna enim,
      interdum eu tempor eu, posuere quis diam. Quisque quis orci dignissim, eleifend
      massa vel, egestas nisi nam ac velit mauris.
    audio: Nemo enim ipsam voluptatem quia voluptas sit aspernatur aut odit aut fugit,
      sed quia consequuntur magni dolores eos qui ratione voluptatem sequi nesciunt.
    pages:
    -
    layout: video
- scope:
    path: ''
    type: en
  values:
    permalink: "/en/video/:path"
    client: Migloko
    embed: Insert iframe code
    image:
    summary: Maecenas consequat lacus a felis dapibus egestas. Vivamus urna enim,
      interdum eu tempor eu, posuere quis diam. Quisque quis orci dignissim, eleifend
      massa vel, egestas nisi nam ac velit mauris.
    audio: Nemo enim ipsam voluptatem quia voluptas sit aspernatur aut odit aut fugit,
      sed quia consequuntur magni dolores eos qui ratione voluptatem sequi nesciunt.
    pages:
    -
    layout: video
- scope:
    path: ''
    type: de
  values:
    permalink: "/de/video/:path"
    client: Migloko
    embed: Insert iframe code
    image:
    summary: Maecenas consequat lacus a felis dapibus egestas. Vivamus urna enim,
      interdum eu tempor eu, posuere quis diam. Quisque quis orci dignissim, eleifend
      massa vel, egestas nisi nam ac velit mauris.
    audio: Nemo enim ipsam voluptatem quia voluptas sit aspernatur aut odit aut fugit,
      sed quia consequuntur magni dolores eos qui ratione voluptatem sequi nesciunt.
    pages:
    -
    layout: video
- scope:
    path: ''
    type: music
  values:
    file:
    client: Hanze Hogeschool
    pages:
    -
- scope:
    path: ''
    type: voice-overs
  values:
    file:
cdn: http://res.cloudinary.com/roosdorp/image/fetch
host: http://finetunemusic.jasperroosdorp.nl/
basehref: http://finetunemusic.jasperroosdorp.nl
urlext:
exclude:
- node_modules
- gulpfile.js
- package.json
- ".DS_Store"
- README.md
- other
- CNAME
- package-lock.json
- _uploads/backup
