---
title: Finetunemusic
timezone: Europe/Amsterdam
collections:
  audio:
    title: Audio
    output: true
  posts:
    title: Guide
    output: true
  uploads:
    title: Uploads
    output: true
  videos:
    title: Video
    output: true
destination: local
keep_files:
- assets
exclude:
- node_modules
- source
- other
- package.json
- gulpfile.js
- README.md
- ".DS_Store"
