---
title: Finetunemusic
timezone: Europe/Amsterdam
collections:
  pages:
    title: Pages
    output: true
  audio:
    title: Audio
    output: true
  video:
    title: Video
    output: true
  uploads:
    title: Uploads
    output: true
defaults:
- scope:
    path: ''
    type: pages
  values:
    layout: page
    permalink: pretty
destination: local
keep_files: [assets]
exclude:
- node_modules
- source
- other
- package.json
- gulpfile.js
- README.md
- ".DS_Store"
