---
title: Finetunemusic
timezone: Europe/Amsterdam
collections:
  music:
    title: Music
    output: false
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
  videos:
    title: Videos
    output: true
  voice-overs:
    title: Voice-Overs
    output: true
defaults:
- scope:
    path: ''
    type: videos
  values:
    is from vimeo: true
    number: 026292034
    summary: 
    audio: 
    layout: video
destination: local
keep_files:
- assets
exclude:
- node_modules
- source
- other
- package.json
- gulpfile.js
- README.md
- ".DS_Store"
